lang: en
title: incubator.to - Tit Petric
description: It is easier to write an incorrect program than understand a correct one.
domain: incubator.to
url: https://incubator.to
ogImage: /assets/social/incubator.to.png
author:
  name: Tit Petric
  email: me@titpetric.com
